### ISSUE TITLE
Error: failed to find request token in session

### ISSUE THREAD

**Issue by realdope** [jaredhanson/passport-linkedin#6]
Hi, I have the following code:

```
  $.passport.use(new $.passport_local.Strategy({
    usernameField: "email"
  }, function(email, password, done) {
    $.auth.authenticate(email, password).then(function(user) {
      done(null, user);
    }).done();
  }));

  console.log("cALLBACK", app.get("frontend_url") + "/auth/linkedin/callback");

  $.passport.use(new $.passport_linkedin.Strategy({
    consumerKey: app.get("linkedin_apikey"),
    consumerSecret: app.get("linkedin_secret"),
    callbackURL: app.get("frontend_url") + "/auth/linkedin/callback"
  }, function(access_token, token_secret, profile, done) {
    $.auth.linkedin(access_token, token_secret, profile).then(function(user) {
      done(null, user);
    }).done();
  }));
```

I have passport-local and passport-linkedin. Both are working in local development environments. However, passport_linkedin doesn't work in production (nodejitsu). I'm getting

```
[08/26 11:20:26 EDT][err] Error: failed to find request token in session
[08/26 11:20:26 EDT][err]     at Strategy.OAuthStrategy.authenticate (/opt/run/snapshot/package/node_modules/passport-linkedin/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:124:54)
[08/26 11:20:26 EDT][err]     at Strategy.authenticate (/opt/run/snapshot/package/node_modules/passport-linkedin/lib/passport-linkedin/strategy.js:118:40)
[08/26 11:20:26 EDT][err]     at attempt (/opt/run/snapshot/package/node_modules/passport/lib/passport/middleware/authenticate.js:243:16)
[08/26 11:20:26 EDT][err]     at Passport.authenticate (/opt/run/snapshot/package/node_modules/passport/lib/passport/middleware/authenticate.js:244:7)
[08/26 11:20:26 EDT][err]     at callbacks (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:161:37)
[08/26 11:20:26 EDT][err]     at param (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:135:11)
[08/26 11:20:26 EDT][err]     at pass (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:142:5)
[08/26 11:20:26 EDT][err]     at Router._dispatch (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:170:5)
[08/26 11:20:26 EDT][err]     at Object.router (/opt/run/snapshot/package/node_modules/express/lib/router/index.js:33:10)
[08/26 11:20:26 EDT][err]     at next (/opt/run/snapshot/package/node_modules/express/node_modules/connect/lib/proto.js:190:15)
```

I've checked the domain name and subdomains, and found no discrepancy there between /auth/linkedin and /auth/linkedin/callback. I don't know what else could contribute to this error.

**Comment by AlmogBaku** [comment]
the solution @cjroebuck helps me too (the callback had `www`).
How can we fix it for every domain.

**Comment by gauravbansal74** [comment]
I am also getting same issue. please help :+1:

**Comment by askucher** [comment]
+1

**Comment by bephrem1** [comment]
+1
